# Generated by Django 4.2.11 on 2024-04-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('cpi', models.FloatField()),
                ('unemployment', models.FloatField()),
                ('is_holiday', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('weekly_sales', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
        ),
    ]
