# Generated by Django 4.2.11 on 2024-04-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesData2',
        ),
    ]
