# Generated by Django 4.2.11 on 2024-04-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis3', '0002_delete_salesdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData2010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('is_holiday', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('weekly_sales', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_data_2010',
            },
        ),
        migrations.CreateModel(
            name='SalesData2011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('is_holiday', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('weekly_sales', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_data_2011',
            },
        ),
        migrations.CreateModel(
            name='SalesData2012',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('is_holiday', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('weekly_sales', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_data_2012',
            },
        ),
    ]
