# Generated by Django 4.2.11 on 2024-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('fuel_price', models.FloatField()),
                ('cpi', models.FloatField()),
                ('dept', models.IntegerField()),
                ('weekly_sales', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
        ),
    ]
